- name: Update all installed packages (dist upgrade)
  gather_facts: true
  become: true
  hosts: all
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      register: update_cache
      until: update_cache is not failed
      retries: 3
      delay: 5

    - name: Upgrade all system packages
      ansible.builtin.apt:
        upgrade: dist
      register: upgrade_packages
      until: upgrade_packages is not failed
      retries: 3
      delay: 5
