---
- name: Ensure mount directory present
  ansible.builtin.file:
    path: /mnt/data
    owner: root
    group: root
    mode: "0755"
    state: directory

- name: Create ext4 filesystem on block storage
  community.general.filesystem:
    fstype: ext4
    dev: /dev/disk/by-id/scsi-0DO_Volume_{{ inventory_hostname }}-vol

- name: Mount volume
  ansible.posix.mount:
    path: /mnt/data
    src: /dev/disk/by-id/scsi-0DO_Volume_{{ inventory_hostname }}-vol
    fstype: ext4
    state: mounted
