---
# Setup attached volumes on clients
- name: Setup volumes
  gather_facts: false
  become: true
  hosts: nimbus,nethermind
  roles:
    - blockstorage

# Setup Nimbus on CL VM using a role that includes consensys.nimbus
- name: Setup Nimbus
  gather_facts: true
  become: true
  hosts: nimbus
  tags: nimbus
  roles:
    - nimbus

# Setup Nethermind on EL VM using personally created role
- name: Setup Nethermind
  gather_facts: true
  become: true
  hosts: nethermind
  tags: nethermind
  roles:
    - nethermind

