---
- name: Ensure we have sane configuration
  block:
    - ansible.builtin.fail:
        msg: You must set "nimbus_version" for this role to run
      when: nimbus_version is not defined

- name: Get IP address to bind to if not provided
  ansible.builtin.include_tasks: network.yml
  when: not nimbus_host_ip

- name: Install nimbus
  ansible.builtin.include_tasks: install.yml
- name: Perform trusted node sync
  ansible.builtin.include_tasks: trusted-node-sync.yml
  when: nimbus_checkpoint_sync_url is defined and nimbus_checkpoint_sync_url != ""

- name: Start beacon
  ansible.builtin.include_tasks: beacon.yml
  when: nimbus_beacon_enabled

- name: Start validator
  ansible.builtin.include_tasks: validator.yml
  when: nimbus_validator_enabled
